// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gps_alarm_ntofiy.proto

package com.glsx.pb;

public final class alarmkafka {
  private alarmkafka() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code gps_alarm_notify.GPS_ALARM_TYPE}
   */
  public enum GPS_ALARM_TYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>COLLISION_ALARM_TYPE = 1;</code>
     *
     * <pre>
     *碰撞告警
     * </pre>
     */
    COLLISION_ALARM_TYPE(0, 1),
    /**
     * <code>LOW_VOLTAGE_ALARM_TYPE = 2;</code>
     *
     * <pre>
     *低电压告警
     * </pre>
     */
    LOW_VOLTAGE_ALARM_TYPE(1, 2),
    /**
     * <code>BLACKOUT_ALARM_TYPE = 3;</code>
     *
     * <pre>
     *断电告警
     * </pre>
     */
    BLACKOUT_ALARM_TYPE(2, 3),
    /**
     * <code>PSEUDOBS_ALARM_TYPE = 4;</code>
     *
     * <pre>
     *伪基站报警
     * </pre>
     */
    PSEUDOBS_ALARM_TYPE(3, 4),
    /**
     * <code>SEPERATE_ALARM_TYPE = 5;</code>
     *
     * <pre>
     *子母分离报警
     * </pre>
     */
    SEPERATE_ALARM_TYPE(4, 5),
    /**
     * <code>SHOCK_ALARM_TYPE = 6;</code>
     *
     * <pre>
     *震动报警
     * </pre>
     */
    SHOCK_ALARM_TYPE(5, 6),
    ;

    /**
     * <code>COLLISION_ALARM_TYPE = 1;</code>
     *
     * <pre>
     *碰撞告警
     * </pre>
     */
    public static final int COLLISION_ALARM_TYPE_VALUE = 1;
    /**
     * <code>LOW_VOLTAGE_ALARM_TYPE = 2;</code>
     *
     * <pre>
     *低电压告警
     * </pre>
     */
    public static final int LOW_VOLTAGE_ALARM_TYPE_VALUE = 2;
    /**
     * <code>BLACKOUT_ALARM_TYPE = 3;</code>
     *
     * <pre>
     *断电告警
     * </pre>
     */
    public static final int BLACKOUT_ALARM_TYPE_VALUE = 3;
    /**
     * <code>PSEUDOBS_ALARM_TYPE = 4;</code>
     *
     * <pre>
     *伪基站报警
     * </pre>
     */
    public static final int PSEUDOBS_ALARM_TYPE_VALUE = 4;
    /**
     * <code>SEPERATE_ALARM_TYPE = 5;</code>
     *
     * <pre>
     *子母分离报警
     * </pre>
     */
    public static final int SEPERATE_ALARM_TYPE_VALUE = 5;
    /**
     * <code>SHOCK_ALARM_TYPE = 6;</code>
     *
     * <pre>
     *震动报警
     * </pre>
     */
    public static final int SHOCK_ALARM_TYPE_VALUE = 6;


    public final int getNumber() { return value; }

    public static GPS_ALARM_TYPE valueOf(int value) {
      switch (value) {
        case 1: return COLLISION_ALARM_TYPE;
        case 2: return LOW_VOLTAGE_ALARM_TYPE;
        case 3: return BLACKOUT_ALARM_TYPE;
        case 4: return PSEUDOBS_ALARM_TYPE;
        case 5: return SEPERATE_ALARM_TYPE;
        case 6: return SHOCK_ALARM_TYPE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GPS_ALARM_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GPS_ALARM_TYPE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GPS_ALARM_TYPE>() {
            public GPS_ALARM_TYPE findValueByNumber(int number) {
              return GPS_ALARM_TYPE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return alarmkafka.getDescriptor().getEnumTypes().get(0);
    }

    private static final GPS_ALARM_TYPE[] VALUES = values();

    public static GPS_ALARM_TYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private GPS_ALARM_TYPE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:gps_alarm_notify.GPS_ALARM_TYPE)
  }

  public interface AlarmNotifyReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string devicesn = 1;
    /**
     * <code>required string devicesn = 1;</code>
     *
     * <pre>
     *设备标识
     * </pre>
     */
    boolean hasDevicesn();
    /**
     * <code>required string devicesn = 1;</code>
     *
     * <pre>
     *设备标识
     * </pre>
     */
    String getDevicesn();
    /**
     * <code>required string devicesn = 1;</code>
     *
     * <pre>
     *设备标识
     * </pre>
     */
    com.google.protobuf.ByteString
        getDevicesnBytes();

    // required uint32 gpstime = 2;
    /**
     * <code>required uint32 gpstime = 2;</code>
     *
     * <pre>
     *服务器时间 1970之后的秒数
     * </pre>
     */
    boolean hasGpstime();
    /**
     * <code>required uint32 gpstime = 2;</code>
     *
     * <pre>
     *服务器时间 1970之后的秒数
     * </pre>
     */
    int getGpstime();

    // required int32 longitude = 3;
    /**
     * <code>required int32 longitude = 3;</code>
     *
     * <pre>
     *报警位置：经度
     * </pre>
     */
    boolean hasLongitude();
    /**
     * <code>required int32 longitude = 3;</code>
     *
     * <pre>
     *报警位置：经度
     * </pre>
     */
    int getLongitude();

    // required int32 latitude = 4;
    /**
     * <code>required int32 latitude = 4;</code>
     *
     * <pre>
     *报警位置：纬度
     * </pre>
     */
    boolean hasLatitude();
    /**
     * <code>required int32 latitude = 4;</code>
     *
     * <pre>
     *报警位置：纬度
     * </pre>
     */
    int getLatitude();

    // required int32 alarmtype = 5;
    /**
     * <code>required int32 alarmtype = 5;</code>
     *
     * <pre>
     *告警类型, 定义见GPS_ALARM_TYPE
     * </pre>
     */
    boolean hasAlarmtype();
    /**
     * <code>required int32 alarmtype = 5;</code>
     *
     * <pre>
     *告警类型, 定义见GPS_ALARM_TYPE
     * </pre>
     */
    int getAlarmtype();

    // required int32 alarmdata = 6;
    /**
     * <code>required int32 alarmdata = 6;</code>
     *
     * <pre>
     *报警数据
     * </pre>
     */
    boolean hasAlarmdata();
    /**
     * <code>required int32 alarmdata = 6;</code>
     *
     * <pre>
     *报警数据
     * </pre>
     */
    int getAlarmdata();

    // required int32 speed = 7;
    /**
     * <code>required int32 speed = 7;</code>
     *
     * <pre>
     *报警数据
     * </pre>
     */
    boolean hasSpeed();
    /**
     * <code>required int32 speed = 7;</code>
     *
     * <pre>
     *报警数据
     * </pre>
     */
    int getSpeed();

    // optional float grange = 8;
    /**
     * <code>optional float grange = 8;</code>
     *
     * <pre>
     *gsensor值
     * </pre>
     */
    boolean hasGrange();
    /**
     * <code>optional float grange = 8;</code>
     *
     * <pre>
     *gsensor值
     * </pre>
     */
    float getGrange();

    // optional string gsensors = 9;
    /**
     * <code>optional string gsensors = 9;</code>
     *
     * <pre>
     *gsensor序列
     * </pre>
     */
    boolean hasGsensors();
    /**
     * <code>optional string gsensors = 9;</code>
     *
     * <pre>
     *gsensor序列
     * </pre>
     */
    String getGsensors();
    /**
     * <code>optional string gsensors = 9;</code>
     *
     * <pre>
     *gsensor序列
     * </pre>
     */
    com.google.protobuf.ByteString
        getGsensorsBytes();

    // optional float accurate = 10;
    /**
     * <code>optional float accurate = 10;</code>
     *
     * <pre>
     *准确率
     * </pre>
     */
    boolean hasAccurate();
    /**
     * <code>optional float accurate = 10;</code>
     *
     * <pre>
     *准确率
     * </pre>
     */
    float getAccurate();

    // optional string task_id = 11;
    /**
     * <code>optional string task_id = 11;</code>
     *
     * <pre>
     *视频关联id,目前只有普方达行车记录仪有此字段
     * </pre>
     */
    boolean hasTaskId();
    /**
     * <code>optional string task_id = 11;</code>
     *
     * <pre>
     *视频关联id,目前只有普方达行车记录仪有此字段
     * </pre>
     */
    String getTaskId();
    /**
     * <code>optional string task_id = 11;</code>
     *
     * <pre>
     *视频关联id,目前只有普方达行车记录仪有此字段
     * </pre>
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();
  }
  /**
   * Protobuf type {@code gps_alarm_notify.AlarmNotifyReq}
   */
  public static final class AlarmNotifyReq extends
      com.google.protobuf.GeneratedMessage
      implements AlarmNotifyReqOrBuilder {
    // Use AlarmNotifyReq.newBuilder() to construct.
    private AlarmNotifyReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AlarmNotifyReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AlarmNotifyReq defaultInstance;
    public static AlarmNotifyReq getDefaultInstance() {
      return defaultInstance;
    }

    public AlarmNotifyReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AlarmNotifyReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              devicesn_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              gpstime_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              longitude_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              latitude_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              alarmtype_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              alarmdata_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              speed_ = input.readInt32();
              break;
            }
            case 69: {
              bitField0_ |= 0x00000080;
              grange_ = input.readFloat();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              gsensors_ = input.readBytes();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000200;
              accurate_ = input.readFloat();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              taskId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return alarmkafka.internal_static_gps_alarm_notify_AlarmNotifyReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return alarmkafka.internal_static_gps_alarm_notify_AlarmNotifyReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AlarmNotifyReq.class, Builder.class);
    }

    public static com.google.protobuf.Parser<AlarmNotifyReq> PARSER =
        new com.google.protobuf.AbstractParser<AlarmNotifyReq>() {
      public AlarmNotifyReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AlarmNotifyReq(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<AlarmNotifyReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string devicesn = 1;
    public static final int DEVICESN_FIELD_NUMBER = 1;
    private Object devicesn_;
    /**
     * <code>required string devicesn = 1;</code>
     *
     * <pre>
     *设备标识
     * </pre>
     */
    public boolean hasDevicesn() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string devicesn = 1;</code>
     *
     * <pre>
     *设备标识
     * </pre>
     */
    public String getDevicesn() {
      Object ref = devicesn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          devicesn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string devicesn = 1;</code>
     *
     * <pre>
     *设备标识
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDevicesnBytes() {
      Object ref = devicesn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        devicesn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint32 gpstime = 2;
    public static final int GPSTIME_FIELD_NUMBER = 2;
    private int gpstime_;
    /**
     * <code>required uint32 gpstime = 2;</code>
     *
     * <pre>
     *服务器时间 1970之后的秒数
     * </pre>
     */
    public boolean hasGpstime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 gpstime = 2;</code>
     *
     * <pre>
     *服务器时间 1970之后的秒数
     * </pre>
     */
    public int getGpstime() {
      return gpstime_;
    }

    // required int32 longitude = 3;
    public static final int LONGITUDE_FIELD_NUMBER = 3;
    private int longitude_;
    /**
     * <code>required int32 longitude = 3;</code>
     *
     * <pre>
     *报警位置：经度
     * </pre>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 longitude = 3;</code>
     *
     * <pre>
     *报警位置：经度
     * </pre>
     */
    public int getLongitude() {
      return longitude_;
    }

    // required int32 latitude = 4;
    public static final int LATITUDE_FIELD_NUMBER = 4;
    private int latitude_;
    /**
     * <code>required int32 latitude = 4;</code>
     *
     * <pre>
     *报警位置：纬度
     * </pre>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 latitude = 4;</code>
     *
     * <pre>
     *报警位置：纬度
     * </pre>
     */
    public int getLatitude() {
      return latitude_;
    }

    // required int32 alarmtype = 5;
    public static final int ALARMTYPE_FIELD_NUMBER = 5;
    private int alarmtype_;
    /**
     * <code>required int32 alarmtype = 5;</code>
     *
     * <pre>
     *告警类型, 定义见GPS_ALARM_TYPE
     * </pre>
     */
    public boolean hasAlarmtype() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 alarmtype = 5;</code>
     *
     * <pre>
     *告警类型, 定义见GPS_ALARM_TYPE
     * </pre>
     */
    public int getAlarmtype() {
      return alarmtype_;
    }

    // required int32 alarmdata = 6;
    public static final int ALARMDATA_FIELD_NUMBER = 6;
    private int alarmdata_;
    /**
     * <code>required int32 alarmdata = 6;</code>
     *
     * <pre>
     *报警数据
     * </pre>
     */
    public boolean hasAlarmdata() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 alarmdata = 6;</code>
     *
     * <pre>
     *报警数据
     * </pre>
     */
    public int getAlarmdata() {
      return alarmdata_;
    }

    // required int32 speed = 7;
    public static final int SPEED_FIELD_NUMBER = 7;
    private int speed_;
    /**
     * <code>required int32 speed = 7;</code>
     *
     * <pre>
     *报警数据
     * </pre>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 speed = 7;</code>
     *
     * <pre>
     *报警数据
     * </pre>
     */
    public int getSpeed() {
      return speed_;
    }

    // optional float grange = 8;
    public static final int GRANGE_FIELD_NUMBER = 8;
    private float grange_;
    /**
     * <code>optional float grange = 8;</code>
     *
     * <pre>
     *gsensor值
     * </pre>
     */
    public boolean hasGrange() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional float grange = 8;</code>
     *
     * <pre>
     *gsensor值
     * </pre>
     */
    public float getGrange() {
      return grange_;
    }

    // optional string gsensors = 9;
    public static final int GSENSORS_FIELD_NUMBER = 9;
    private Object gsensors_;
    /**
     * <code>optional string gsensors = 9;</code>
     *
     * <pre>
     *gsensor序列
     * </pre>
     */
    public boolean hasGsensors() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string gsensors = 9;</code>
     *
     * <pre>
     *gsensor序列
     * </pre>
     */
    public String getGsensors() {
      Object ref = gsensors_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gsensors_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string gsensors = 9;</code>
     *
     * <pre>
     *gsensor序列
     * </pre>
     */
    public com.google.protobuf.ByteString
        getGsensorsBytes() {
      Object ref = gsensors_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        gsensors_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional float accurate = 10;
    public static final int ACCURATE_FIELD_NUMBER = 10;
    private float accurate_;
    /**
     * <code>optional float accurate = 10;</code>
     *
     * <pre>
     *准确率
     * </pre>
     */
    public boolean hasAccurate() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional float accurate = 10;</code>
     *
     * <pre>
     *准确率
     * </pre>
     */
    public float getAccurate() {
      return accurate_;
    }

    // optional string task_id = 11;
    public static final int TASK_ID_FIELD_NUMBER = 11;
    private Object taskId_;
    /**
     * <code>optional string task_id = 11;</code>
     *
     * <pre>
     *视频关联id,目前只有普方达行车记录仪有此字段
     * </pre>
     */
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string task_id = 11;</code>
     *
     * <pre>
     *视频关联id,目前只有普方达行车记录仪有此字段
     * </pre>
     */
    public String getTaskId() {
      Object ref = taskId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string task_id = 11;</code>
     *
     * <pre>
     *视频关联id,目前只有普方达行车记录仪有此字段
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      devicesn_ = "";
      gpstime_ = 0;
      longitude_ = 0;
      latitude_ = 0;
      alarmtype_ = 0;
      alarmdata_ = 0;
      speed_ = 0;
      grange_ = 0F;
      gsensors_ = "";
      accurate_ = 0F;
      taskId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDevicesn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGpstime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAlarmtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAlarmdata()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDevicesnBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, gpstime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, longitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, latitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, alarmtype_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, alarmdata_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, speed_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFloat(8, grange_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getGsensorsBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeFloat(10, accurate_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getTaskIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDevicesnBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, gpstime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, longitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, latitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, alarmtype_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, alarmdata_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, speed_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, grange_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getGsensorsBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, accurate_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getTaskIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static AlarmNotifyReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AlarmNotifyReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AlarmNotifyReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AlarmNotifyReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AlarmNotifyReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AlarmNotifyReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static AlarmNotifyReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static AlarmNotifyReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static AlarmNotifyReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AlarmNotifyReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(AlarmNotifyReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gps_alarm_notify.AlarmNotifyReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements AlarmNotifyReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return alarmkafka.internal_static_gps_alarm_notify_AlarmNotifyReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return alarmkafka.internal_static_gps_alarm_notify_AlarmNotifyReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AlarmNotifyReq.class, Builder.class);
      }

      // Construct using protoBuffer.alarmkafka.AlarmNotifyReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        devicesn_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        gpstime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        latitude_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        alarmtype_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        alarmdata_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        grange_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        gsensors_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        accurate_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000200);
        taskId_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return alarmkafka.internal_static_gps_alarm_notify_AlarmNotifyReq_descriptor;
      }

      public AlarmNotifyReq getDefaultInstanceForType() {
        return AlarmNotifyReq.getDefaultInstance();
      }

      public AlarmNotifyReq build() {
        AlarmNotifyReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AlarmNotifyReq buildPartial() {
        AlarmNotifyReq result = new AlarmNotifyReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.devicesn_ = devicesn_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gpstime_ = gpstime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.alarmtype_ = alarmtype_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.alarmdata_ = alarmdata_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.grange_ = grange_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.gsensors_ = gsensors_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.accurate_ = accurate_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.taskId_ = taskId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AlarmNotifyReq) {
          return mergeFrom((AlarmNotifyReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AlarmNotifyReq other) {
        if (other == AlarmNotifyReq.getDefaultInstance()) return this;
        if (other.hasDevicesn()) {
          bitField0_ |= 0x00000001;
          devicesn_ = other.devicesn_;
          onChanged();
        }
        if (other.hasGpstime()) {
          setGpstime(other.getGpstime());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasAlarmtype()) {
          setAlarmtype(other.getAlarmtype());
        }
        if (other.hasAlarmdata()) {
          setAlarmdata(other.getAlarmdata());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasGrange()) {
          setGrange(other.getGrange());
        }
        if (other.hasGsensors()) {
          bitField0_ |= 0x00000100;
          gsensors_ = other.gsensors_;
          onChanged();
        }
        if (other.hasAccurate()) {
          setAccurate(other.getAccurate());
        }
        if (other.hasTaskId()) {
          bitField0_ |= 0x00000400;
          taskId_ = other.taskId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDevicesn()) {
          
          return false;
        }
        if (!hasGpstime()) {
          
          return false;
        }
        if (!hasLongitude()) {
          
          return false;
        }
        if (!hasLatitude()) {
          
          return false;
        }
        if (!hasAlarmtype()) {
          
          return false;
        }
        if (!hasAlarmdata()) {
          
          return false;
        }
        if (!hasSpeed()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AlarmNotifyReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AlarmNotifyReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string devicesn = 1;
      private Object devicesn_ = "";
      /**
       * <code>required string devicesn = 1;</code>
       *
       * <pre>
       *设备标识
       * </pre>
       */
      public boolean hasDevicesn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string devicesn = 1;</code>
       *
       * <pre>
       *设备标识
       * </pre>
       */
      public String getDevicesn() {
        Object ref = devicesn_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          devicesn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string devicesn = 1;</code>
       *
       * <pre>
       *设备标识
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDevicesnBytes() {
        Object ref = devicesn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          devicesn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string devicesn = 1;</code>
       *
       * <pre>
       *设备标识
       * </pre>
       */
      public Builder setDevicesn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        devicesn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string devicesn = 1;</code>
       *
       * <pre>
       *设备标识
       * </pre>
       */
      public Builder clearDevicesn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        devicesn_ = getDefaultInstance().getDevicesn();
        onChanged();
        return this;
      }
      /**
       * <code>required string devicesn = 1;</code>
       *
       * <pre>
       *设备标识
       * </pre>
       */
      public Builder setDevicesnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        devicesn_ = value;
        onChanged();
        return this;
      }

      // required uint32 gpstime = 2;
      private int gpstime_ ;
      /**
       * <code>required uint32 gpstime = 2;</code>
       *
       * <pre>
       *服务器时间 1970之后的秒数
       * </pre>
       */
      public boolean hasGpstime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 gpstime = 2;</code>
       *
       * <pre>
       *服务器时间 1970之后的秒数
       * </pre>
       */
      public int getGpstime() {
        return gpstime_;
      }
      /**
       * <code>required uint32 gpstime = 2;</code>
       *
       * <pre>
       *服务器时间 1970之后的秒数
       * </pre>
       */
      public Builder setGpstime(int value) {
        bitField0_ |= 0x00000002;
        gpstime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 gpstime = 2;</code>
       *
       * <pre>
       *服务器时间 1970之后的秒数
       * </pre>
       */
      public Builder clearGpstime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gpstime_ = 0;
        onChanged();
        return this;
      }

      // required int32 longitude = 3;
      private int longitude_ ;
      /**
       * <code>required int32 longitude = 3;</code>
       *
       * <pre>
       *报警位置：经度
       * </pre>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 longitude = 3;</code>
       *
       * <pre>
       *报警位置：经度
       * </pre>
       */
      public int getLongitude() {
        return longitude_;
      }
      /**
       * <code>required int32 longitude = 3;</code>
       *
       * <pre>
       *报警位置：经度
       * </pre>
       */
      public Builder setLongitude(int value) {
        bitField0_ |= 0x00000004;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 longitude = 3;</code>
       *
       * <pre>
       *报警位置：经度
       * </pre>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        longitude_ = 0;
        onChanged();
        return this;
      }

      // required int32 latitude = 4;
      private int latitude_ ;
      /**
       * <code>required int32 latitude = 4;</code>
       *
       * <pre>
       *报警位置：纬度
       * </pre>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 latitude = 4;</code>
       *
       * <pre>
       *报警位置：纬度
       * </pre>
       */
      public int getLatitude() {
        return latitude_;
      }
      /**
       * <code>required int32 latitude = 4;</code>
       *
       * <pre>
       *报警位置：纬度
       * </pre>
       */
      public Builder setLatitude(int value) {
        bitField0_ |= 0x00000008;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 latitude = 4;</code>
       *
       * <pre>
       *报警位置：纬度
       * </pre>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000008);
        latitude_ = 0;
        onChanged();
        return this;
      }

      // required int32 alarmtype = 5;
      private int alarmtype_ ;
      /**
       * <code>required int32 alarmtype = 5;</code>
       *
       * <pre>
       *告警类型, 定义见GPS_ALARM_TYPE
       * </pre>
       */
      public boolean hasAlarmtype() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 alarmtype = 5;</code>
       *
       * <pre>
       *告警类型, 定义见GPS_ALARM_TYPE
       * </pre>
       */
      public int getAlarmtype() {
        return alarmtype_;
      }
      /**
       * <code>required int32 alarmtype = 5;</code>
       *
       * <pre>
       *告警类型, 定义见GPS_ALARM_TYPE
       * </pre>
       */
      public Builder setAlarmtype(int value) {
        bitField0_ |= 0x00000010;
        alarmtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 alarmtype = 5;</code>
       *
       * <pre>
       *告警类型, 定义见GPS_ALARM_TYPE
       * </pre>
       */
      public Builder clearAlarmtype() {
        bitField0_ = (bitField0_ & ~0x00000010);
        alarmtype_ = 0;
        onChanged();
        return this;
      }

      // required int32 alarmdata = 6;
      private int alarmdata_ ;
      /**
       * <code>required int32 alarmdata = 6;</code>
       *
       * <pre>
       *报警数据
       * </pre>
       */
      public boolean hasAlarmdata() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 alarmdata = 6;</code>
       *
       * <pre>
       *报警数据
       * </pre>
       */
      public int getAlarmdata() {
        return alarmdata_;
      }
      /**
       * <code>required int32 alarmdata = 6;</code>
       *
       * <pre>
       *报警数据
       * </pre>
       */
      public Builder setAlarmdata(int value) {
        bitField0_ |= 0x00000020;
        alarmdata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 alarmdata = 6;</code>
       *
       * <pre>
       *报警数据
       * </pre>
       */
      public Builder clearAlarmdata() {
        bitField0_ = (bitField0_ & ~0x00000020);
        alarmdata_ = 0;
        onChanged();
        return this;
      }

      // required int32 speed = 7;
      private int speed_ ;
      /**
       * <code>required int32 speed = 7;</code>
       *
       * <pre>
       *报警数据
       * </pre>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 speed = 7;</code>
       *
       * <pre>
       *报警数据
       * </pre>
       */
      public int getSpeed() {
        return speed_;
      }
      /**
       * <code>required int32 speed = 7;</code>
       *
       * <pre>
       *报警数据
       * </pre>
       */
      public Builder setSpeed(int value) {
        bitField0_ |= 0x00000040;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 speed = 7;</code>
       *
       * <pre>
       *报警数据
       * </pre>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000040);
        speed_ = 0;
        onChanged();
        return this;
      }

      // optional float grange = 8;
      private float grange_ ;
      /**
       * <code>optional float grange = 8;</code>
       *
       * <pre>
       *gsensor值
       * </pre>
       */
      public boolean hasGrange() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional float grange = 8;</code>
       *
       * <pre>
       *gsensor值
       * </pre>
       */
      public float getGrange() {
        return grange_;
      }
      /**
       * <code>optional float grange = 8;</code>
       *
       * <pre>
       *gsensor值
       * </pre>
       */
      public Builder setGrange(float value) {
        bitField0_ |= 0x00000080;
        grange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float grange = 8;</code>
       *
       * <pre>
       *gsensor值
       * </pre>
       */
      public Builder clearGrange() {
        bitField0_ = (bitField0_ & ~0x00000080);
        grange_ = 0F;
        onChanged();
        return this;
      }

      // optional string gsensors = 9;
      private Object gsensors_ = "";
      /**
       * <code>optional string gsensors = 9;</code>
       *
       * <pre>
       *gsensor序列
       * </pre>
       */
      public boolean hasGsensors() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string gsensors = 9;</code>
       *
       * <pre>
       *gsensor序列
       * </pre>
       */
      public String getGsensors() {
        Object ref = gsensors_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          gsensors_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string gsensors = 9;</code>
       *
       * <pre>
       *gsensor序列
       * </pre>
       */
      public com.google.protobuf.ByteString
          getGsensorsBytes() {
        Object ref = gsensors_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          gsensors_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gsensors = 9;</code>
       *
       * <pre>
       *gsensor序列
       * </pre>
       */
      public Builder setGsensors(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        gsensors_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gsensors = 9;</code>
       *
       * <pre>
       *gsensor序列
       * </pre>
       */
      public Builder clearGsensors() {
        bitField0_ = (bitField0_ & ~0x00000100);
        gsensors_ = getDefaultInstance().getGsensors();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gsensors = 9;</code>
       *
       * <pre>
       *gsensor序列
       * </pre>
       */
      public Builder setGsensorsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        gsensors_ = value;
        onChanged();
        return this;
      }

      // optional float accurate = 10;
      private float accurate_ ;
      /**
       * <code>optional float accurate = 10;</code>
       *
       * <pre>
       *准确率
       * </pre>
       */
      public boolean hasAccurate() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional float accurate = 10;</code>
       *
       * <pre>
       *准确率
       * </pre>
       */
      public float getAccurate() {
        return accurate_;
      }
      /**
       * <code>optional float accurate = 10;</code>
       *
       * <pre>
       *准确率
       * </pre>
       */
      public Builder setAccurate(float value) {
        bitField0_ |= 0x00000200;
        accurate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float accurate = 10;</code>
       *
       * <pre>
       *准确率
       * </pre>
       */
      public Builder clearAccurate() {
        bitField0_ = (bitField0_ & ~0x00000200);
        accurate_ = 0F;
        onChanged();
        return this;
      }

      // optional string task_id = 11;
      private Object taskId_ = "";
      /**
       * <code>optional string task_id = 11;</code>
       *
       * <pre>
       *视频关联id,目前只有普方达行车记录仪有此字段
       * </pre>
       */
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string task_id = 11;</code>
       *
       * <pre>
       *视频关联id,目前只有普方达行车记录仪有此字段
       * </pre>
       */
      public String getTaskId() {
        Object ref = taskId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string task_id = 11;</code>
       *
       * <pre>
       *视频关联id,目前只有普方达行车记录仪有此字段
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string task_id = 11;</code>
       *
       * <pre>
       *视频关联id,目前只有普方达行车记录仪有此字段
       * </pre>
       */
      public Builder setTaskId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string task_id = 11;</code>
       *
       * <pre>
       *视频关联id,目前只有普方达行车记录仪有此字段
       * </pre>
       */
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000400);
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string task_id = 11;</code>
       *
       * <pre>
       *视频关联id,目前只有普方达行车记录仪有此字段
       * </pre>
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        taskId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gps_alarm_notify.AlarmNotifyReq)
    }

    static {
      defaultInstance = new AlarmNotifyReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gps_alarm_notify.AlarmNotifyReq)
  }

  public interface OneKeyHelpResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 mtype = 1;
    /**
     * <code>required uint32 mtype = 1;</code>
     */
    boolean hasMtype();
    /**
     * <code>required uint32 mtype = 1;</code>
     */
    int getMtype();

    // required string url = 2;
    /**
     * <code>required string url = 2;</code>
     */
    boolean hasUrl();
    /**
     * <code>required string url = 2;</code>
     */
    String getUrl();
    /**
     * <code>required string url = 2;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    // required string task_id = 3;
    /**
     * <code>required string task_id = 3;</code>
     */
    boolean hasTaskId();
    /**
     * <code>required string task_id = 3;</code>
     */
    String getTaskId();
    /**
     * <code>required string task_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();
  }
  /**
   * Protobuf type {@code gps_alarm_notify.OneKeyHelpRes}
   *
   * <pre>
   *碰撞视频url
   * </pre>
   */
  public static final class OneKeyHelpRes extends
      com.google.protobuf.GeneratedMessage
      implements OneKeyHelpResOrBuilder {
    // Use OneKeyHelpRes.newBuilder() to construct.
    private OneKeyHelpRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OneKeyHelpRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OneKeyHelpRes defaultInstance;
    public static OneKeyHelpRes getDefaultInstance() {
      return defaultInstance;
    }

    public OneKeyHelpRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OneKeyHelpRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              mtype_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              url_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              taskId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return alarmkafka.internal_static_gps_alarm_notify_OneKeyHelpRes_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return alarmkafka.internal_static_gps_alarm_notify_OneKeyHelpRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OneKeyHelpRes.class, Builder.class);
    }

    public static com.google.protobuf.Parser<OneKeyHelpRes> PARSER =
        new com.google.protobuf.AbstractParser<OneKeyHelpRes>() {
      public OneKeyHelpRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OneKeyHelpRes(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<OneKeyHelpRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 mtype = 1;
    public static final int MTYPE_FIELD_NUMBER = 1;
    private int mtype_;
    /**
     * <code>required uint32 mtype = 1;</code>
     */
    public boolean hasMtype() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 mtype = 1;</code>
     */
    public int getMtype() {
      return mtype_;
    }

    // required string url = 2;
    public static final int URL_FIELD_NUMBER = 2;
    private Object url_;
    /**
     * <code>required string url = 2;</code>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string url = 2;</code>
     */
    public String getUrl() {
      Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string url = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string task_id = 3;
    public static final int TASK_ID_FIELD_NUMBER = 3;
    private Object taskId_;
    /**
     * <code>required string task_id = 3;</code>
     */
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string task_id = 3;</code>
     */
    public String getTaskId() {
      Object ref = taskId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string task_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      mtype_ = 0;
      url_ = "";
      taskId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTaskId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, mtype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTaskIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, mtype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTaskIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static OneKeyHelpRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OneKeyHelpRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OneKeyHelpRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OneKeyHelpRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OneKeyHelpRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static OneKeyHelpRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static OneKeyHelpRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static OneKeyHelpRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static OneKeyHelpRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static OneKeyHelpRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(OneKeyHelpRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gps_alarm_notify.OneKeyHelpRes}
     *
     * <pre>
     *碰撞视频url
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements OneKeyHelpResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return alarmkafka.internal_static_gps_alarm_notify_OneKeyHelpRes_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return alarmkafka.internal_static_gps_alarm_notify_OneKeyHelpRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OneKeyHelpRes.class, Builder.class);
      }

      // Construct using protoBuffer.alarmkafka.OneKeyHelpRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mtype_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        taskId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return alarmkafka.internal_static_gps_alarm_notify_OneKeyHelpRes_descriptor;
      }

      public OneKeyHelpRes getDefaultInstanceForType() {
        return OneKeyHelpRes.getDefaultInstance();
      }

      public OneKeyHelpRes build() {
        OneKeyHelpRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public OneKeyHelpRes buildPartial() {
        OneKeyHelpRes result = new OneKeyHelpRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mtype_ = mtype_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.taskId_ = taskId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OneKeyHelpRes) {
          return mergeFrom((OneKeyHelpRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OneKeyHelpRes other) {
        if (other == OneKeyHelpRes.getDefaultInstance()) return this;
        if (other.hasMtype()) {
          setMtype(other.getMtype());
        }
        if (other.hasUrl()) {
          bitField0_ |= 0x00000002;
          url_ = other.url_;
          onChanged();
        }
        if (other.hasTaskId()) {
          bitField0_ |= 0x00000004;
          taskId_ = other.taskId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMtype()) {
          
          return false;
        }
        if (!hasUrl()) {
          
          return false;
        }
        if (!hasTaskId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OneKeyHelpRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OneKeyHelpRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 mtype = 1;
      private int mtype_ ;
      /**
       * <code>required uint32 mtype = 1;</code>
       */
      public boolean hasMtype() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 mtype = 1;</code>
       */
      public int getMtype() {
        return mtype_;
      }
      /**
       * <code>required uint32 mtype = 1;</code>
       */
      public Builder setMtype(int value) {
        bitField0_ |= 0x00000001;
        mtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 mtype = 1;</code>
       */
      public Builder clearMtype() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mtype_ = 0;
        onChanged();
        return this;
      }

      // required string url = 2;
      private Object url_ = "";
      /**
       * <code>required string url = 2;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string url = 2;</code>
       */
      public String getUrl() {
        Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string url = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string url = 2;</code>
       */
      public Builder setUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 2;</code>
       */
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 2;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        url_ = value;
        onChanged();
        return this;
      }

      // required string task_id = 3;
      private Object taskId_ = "";
      /**
       * <code>required string task_id = 3;</code>
       */
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string task_id = 3;</code>
       */
      public String getTaskId() {
        Object ref = taskId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string task_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string task_id = 3;</code>
       */
      public Builder setTaskId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string task_id = 3;</code>
       */
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <code>required string task_id = 3;</code>
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        taskId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gps_alarm_notify.OneKeyHelpRes)
    }

    static {
      defaultInstance = new OneKeyHelpRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gps_alarm_notify.OneKeyHelpRes)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gps_alarm_notify_AlarmNotifyReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gps_alarm_notify_AlarmNotifyReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gps_alarm_notify_OneKeyHelpRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gps_alarm_notify_OneKeyHelpRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026gps_alarm_ntofiy.proto\022\020gps_alarm_noti" +
      "fy\"\322\001\n\016AlarmNotifyReq\022\020\n\010devicesn\030\001 \002(\t\022" +
      "\017\n\007gpstime\030\002 \002(\r\022\021\n\tlongitude\030\003 \002(\005\022\020\n\010l" +
      "atitude\030\004 \002(\005\022\021\n\talarmtype\030\005 \002(\005\022\021\n\talar" +
      "mdata\030\006 \002(\005\022\r\n\005speed\030\007 \002(\005\022\016\n\006grange\030\010 \001" +
      "(\002\022\020\n\010gsensors\030\t \001(\t\022\020\n\010accurate\030\n \001(\002\022\017" +
      "\n\007task_id\030\013 \001(\t\"<\n\rOneKeyHelpRes\022\r\n\005mtyp" +
      "e\030\001 \002(\r\022\013\n\003url\030\002 \002(\t\022\017\n\007task_id\030\003 \002(\t*\247\001" +
      "\n\016GPS_ALARM_TYPE\022\030\n\024COLLISION_ALARM_TYPE" +
      "\020\001\022\032\n\026LOW_VOLTAGE_ALARM_TYPE\020\002\022\027\n\023BLACKO",
      "UT_ALARM_TYPE\020\003\022\027\n\023PSEUDOBS_ALARM_TYPE\020\004" +
      "\022\027\n\023SEPERATE_ALARM_TYPE\020\005\022\024\n\020SHOCK_ALARM" +
      "_TYPE\020\006B\031\n\013protoBufferB\nalarmkafka"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gps_alarm_notify_AlarmNotifyReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gps_alarm_notify_AlarmNotifyReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gps_alarm_notify_AlarmNotifyReq_descriptor,
              new String[] { "Devicesn", "Gpstime", "Longitude", "Latitude", "Alarmtype", "Alarmdata", "Speed", "Grange", "Gsensors", "Accurate", "TaskId", });
          internal_static_gps_alarm_notify_OneKeyHelpRes_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_gps_alarm_notify_OneKeyHelpRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gps_alarm_notify_OneKeyHelpRes_descriptor,
              new String[] { "Mtype", "Url", "TaskId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
